export const FLAVORS = [
  'Buffalo',
  'Honey BBQ',
  'Bourbon Honey Mustard',
  'Teriyaki',
  'Asian Zing',
  'Hot BBQ',
  'Desert Heat',
  'Plain',
  'Sweet BBQ',
  'Salt and Vinegar',
  'Blazin',
  'Hot',
  'Spicy Garlic',
  'Wild',
  'Caribbean Jerk',
  'Mild',
  'Lemon Pepper',
  'Thai Curry',
  'Chipotle BBQ',
  'Medium',
  'Parmesan Garlic',
  'Mango Habanero',
  'Jammin Jalapeno',
]